Pl samtools stats
ewels/MultiQC pull request #1972
Opened 2023-08-09 15:17 UTC by lindenb

This PR fixes a problem with `samtools stats` https://github.com/ewels/MultiQC/issues/1971

I'm not a python dev, so I hope it's ok !

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` has been updated

2023-08-09 20:55 UTC, ewels commented
Thanks for this @lindenb!

It looks like this metric has been completely missed until now..

* Is it _always_ there? (It'll crash if not currently)
* Are there any plots / tables that should include this as a category as well?

Cheers,

Phil

2023-08-23 10:30 UTC, vladsavelyev commented
@lindenb - thanks a lot for the contribution, it looks good to me, but would you be able to submit a test example that reproduces the bug into [MultiQC_TestData](https://github.com/ewels/MultiQC_TestData)? Thank you!

2023-08-23 10:38 UTC, vladsavelyev requested changes
Asking for a test example, otherwise good to me

2023-08-23 13:49 UTC, lindenb commented
> @lindenb - thanks a lot for the contribution, it looks good to me, but would you be able to submit a test example that reproduces the bug into [MultiQC_TestData](https://github.com/ewels/MultiQC_TestData)? Thank you!

@vladsavelyev thanks for the review & done : https://github.com/ewels/MultiQC_TestData/pull/267

2023-08-24 08:52 UTC, vladsavelyev approved these changes
Looks good to me!

2023-08-24 09:33 UTC, ewels approved these changes

2023-08-24 09:34 UTC, ewels commented
Thanks @lindenb!

2023-08-24 09:36 UTC, merged