qualimap bamqc: add percentage on target
ewels/MultiQC pull request #2020
Opened 2023-08-31 13:58 UTC by FerriolCalvet

Solving this issue: #2019 

- [x] This comment contains a description of changes (with reason)
This is explained in the issue referenced above. But basically I am adding an extra column to the output table of Qualimap BAMQC. This value is already present in the default output of Qualimap BAMQC. It is the **(97.14%)**.
![image](https://github.com/ewels/MultiQC/assets/38539786/1407cc05-88d5-4725-8837-eada9aa9776c)

- [ ] `CHANGELOG.md` has been updated

2023-08-31 15:48 UTC, vladsavelyev commented on multiqc/modules/qualimap/QM_BamQC.py
> +        self.general_stats_data[s_name]["regions_percentage_inside"] = d["regions_percentage_inside"]
I'd rename it slightly for consistency with other percentage metrics
```suggestion
        d["percentage_aligned_on_target"] = (d["regions_mapped_reads"] / d["mapped_reads"]) * 100
        self.general_stats_data[s_name]["percentage_aligned_on_target"] = d["percentage_aligned_on_target"]
```

2023-08-31 15:49 UTC, vladsavelyev commented on multiqc/modules/qualimap/QM_BamQC.py
> +    self.general_stats_headers["regions_percentage_inside"] = {
```suggestion
    self.general_stats_headers["percentage_aligned_on_target"] = {
```

2023-08-31 15:53 UTC, vladsavelyev approved these changes
Thank you! Looks good to me. 

I think it make sense to change the title of the existing `regions_mapped_reads` metric from `"{} Aligned"` to `"{} On target"`, otherwise it has the same name as the overall number of mapped reads.

2023-09-01 09:49 UTC, vladsavelyev requested changes
Just rename the `regions_mapped_reads` metric from "{} Aligned" to "{} On target", please :)

2023-09-01 15:40 UTC, vladsavelyev approved these changes

2023-09-14 22:04 UTC, ewels approved these changes
Looks good! Couple of minor pedantic comments, will fix quickly myself now.

2023-09-14 22:04 UTC, ewels commented on multiqc/modules/qualimap/QM_BamQC.py
> +        d["percentage_aligned_on_target"] = (d["regions_mapped_reads"] / d["mapped_reads"]) * 100
It's good to force a float by doing `* 100.0`

2023-09-14 22:04 UTC, ewels commented on multiqc/modules/qualimap/QM_BamQC.py
> +        self.general_stats_data[s_name]["percentage_aligned_on_target"] = d["percentage_aligned_on_target"]
This is ripe for a `ZeroDivisionError`!

Also, I'm not sure that it helps much to break this out into a new key in `d`?

2023-09-14 22:04 UTC, ewels commented on multiqc/modules/qualimap/QM_BamQC.py
> +    self.general_stats_headers["percentage_aligned_on_target"] = {
I think it makes sense to have this to the left of the more generic columns like "M Aligned", as it's a subset. So better to move further up the code basically.

2023-09-14 22:27 UTC, ewels commented
I realised that several of my review comments also applied to existing code within the module! So was a good opportunity to clean those bits up as well ✅ 

Many thanks for this @FerriolCalvet!

2023-09-14 22:29 UTC, merged