New module: seqera_cli
ewels/MultiQC pull request #2151
Opened 2023-10-25 17:00 UTC by vladsavelyev

Parses `runs_*.tar.gz` dumps containing logs and stats from a Seqera Platform run. To be triggered in the https://github.com/seqeralabs/nf-aggregate workflow. 

Note that binary files by default are ignored by MultiQC, so you need to set `ignore_images: false` in the MultiQC config to make it parse the input tar-gz file. This can be done via the CLI:

```sh
multiqc -m seqera_cli test_data/data/modules/seqera_cli -f -v --cl-config "ignore_images: false"
```

2023-10-25 19:34 UTC, ewels commented
Given that the tar step is from the workflow and not from the Seqera CLI itself, I think we should also cater for uncompressed files. Then can handle the custom stuff in the pipeline but it stays as general use as possible.

2023-10-25 19:40 UTC, drpatelh commented
The Seqera CLI natively dumps tar files. I was going to uncompress them in the same process that dumps the run info but if we don't have to then that would be a bonus. Supporting both would be great. The JSON files all have standard names so will be easy to scrape if we stage each run in its individual directory / archive.

2023-10-25 20:47 UTC, vladsavelyev commented
Added support for both compressed and uncompressed dumps. Also added a barplot and parsing of the platform version.

2023-10-27 09:21 UTC, ewels commented
> Figure out how to better present start date/end date

Maybe show a duration as a column, keep start + end dates but hide by default.

2023-10-27 09:48 UTC, ewels commented
👉🏻  Should specify the task status order + colours in the bar plot to match Tower:

* Pending: `#8f4199`
* Submitted: `#e68642`
* Running: `#4256e7`
* Cached: `#939598`
* Succeeded: `#28ae61`
* Failed: `#e7363e`

2023-11-01 10:26 UTC, ewels approved these changes
Minor comments, otherwise LGTM!

2023-11-01 10:26 UTC, ewels commented on docs/core/development/modules.md
> +    value to float(), and if it fails, it will leave the value as a string without
```suggestion
    value to `float()`, and if it fails, it will leave the value as a string without
```

2023-11-01 10:26 UTC, ewels commented on docs/core/development/modules.md
> +    color code and table sorting. By default, MultiQC attempt to convert each
```suggestion
    color code. By default, MultiQC attempt to convert each
```

2023-11-01 10:26 UTC, ewels commented on docs/core/development/modules.md
> +    color code and sorting.
```suggestion
    color code.
```

2023-11-01 11:51 UTC, ewels commented
LGTM to me to merge, waiting on review from @drpatelh before hitting the button.

2023-11-01 12:01 UTC, ewels commented on multiqc/modules/seqera_cli/seqera_cli.py
> +            doi="10.1016/j.ajhg.2017.01.017",
This is showing the citation for Peddy 😅 

I wonder if we can have some kind of CI check that looks for duplicated DOIs. Might be some valid reasons, but I bet that most would be accidental copy+paste artefacts.
```suggestion
            # doi="",  # No DOI for this tool
```

2023-11-01 12:19 UTC, ewels commented
Suggestion: Move CPU time and Cost columns up, alongside pipeline duration. These 3 columns are likely typically the most interesting.

2023-11-01 12:46 UTC, robsyme requested changes
We know that cpuEfficiency and memoryEfficiency will always be percentages, so should format as such.

2023-11-01 12:46 UTC, robsyme commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                "format": "{:,.2f}",
```suggestion
                "format": "{:,.2f}",
                "suffix": "%",
                "max": 100,
```

2023-11-01 12:46 UTC, robsyme commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                "format": "{:,.2f}",
```suggestion
                "format": "{:,.2f}",
                "suffix": "%",
                "max": 100, 
```

2023-11-01 12:57 UTC, drpatelh commented
Initial comments based on report @ewels sent to me:


In General stats:

### Change names in header:

- [ ]  `Sample Name` -> `Run ID`
- [ ] `Duration` -> `Wall Time`
- [ ] `Cost` -> `Estimated Cost ($)`
- [ ] [NEW] `Pipeline version`

### Default column order in (after renaming based on above):

- [ ] `Repository`
- [ ] `Pipeline version`
- [ ] `Run ID`
- [ ] `Wall Time`
- [ ] `CPU Time`
- [ ] `Estimated Cost ($)`
- [ ] `Read GB`
- [ ] `Write GB`
- [ ] `CPU Efficiency`
- [ ] `Memory Efficiency`

### Default table sorting

- [ ] First by `Repository` and then by `CPU hours`

### Check Wall time calculation

- [ ] For Run ID: `1h5PlYK4uXvNyE` there is a small discrepancy in Duration (9:09:11; MultiQC) vs Wall time (9:09:31; [Seqera Platform](https://tower.nf/orgs/seqeralabs/workspaces/benchmarks/watch/1h5PlYK4uXvNyE)). Are we calculating this correctly? There appears to be a consistent discrepancy for other runs too so we will need to double-check this.

### Process status plot

![image](https://github.com/ewels/MultiQC/assets/23529759/bcbba705-a308-480d-8153-ea9fc84826a7)

- [ ] Remove the  "Versions: 2.6.0, 3.3.2, 3.12.0" next to the `Seqera Platform CLI` header. Doesn't add make any sense having that there and better to include pipeline versions in the General stats table
- [ ] Change x-axis labels to repository name and instead show Run id on hover.
- [ ] The DOI in the description under the header points to something random and needs to be removed.

### Additional Plots

It would be great to at least have bar plots for the more pertinent metrics so they can be dumped directly into presentations if required rather than having to generate them via another tool:

- [ ] `CPU Time`
- [ ] `Wall Time`
- [ ] `Estimated cost ($)`

###  Enhancements

- [ ] Can we include a link to the actual run in Seqera Platform. Can't find a run URL in the JSON files so might need to add that in as an enhancement later.
- [ ] Include run labels in the report for filtering. I will take a look at this now.
- [ ] Include Nextflow and Seqera Platform version in stats

Let me know when you have made these changes and regenerated the report and I'll take another look. Thank you!! Looking great already.

2023-11-01 13:18 UTC, ewels commented
>  `Sample Name` -> `Run ID`

Can't do this in the General Stats table, but we could move all of these out into a module-specific table where it is possible. If there are no other modules running it'll look essentially the same.

> Default table sorting

MultiQC does not have this concept, it'll always be sorted by the primary identifier - the run ID in this case.

>  Remove the "Versions: 2.6.0, 3.3.2, 3.12.0" next to the Seqera Platform CLI header. Doesn't make any sense having that there and better to include pipeline versions in the General stats table

Disagree on this point - that's the version of the CLI that was used. It's a core MultiQC feature now, not sure that it hurts to report this?

> Change x-axis labels to repository name and instead show Run id on hover.

Not sure if this is possible, I have a feeling that these need to be unique during report generation (though can be renamed interactively).

2023-11-01 13:24 UTC, drpatelh commented
>> Sample Name -> Run ID

> Can't do this in the General Stats table, but we could move all of these out into a module-specific table where it is possible. If there are no other modules running it'll look essentially the same.

Ok, happy to see what the alternative looks like. Sample Name is misleading in this context.

>> Default table sorting

> MultiQC does not have this concept, it'll always be sorted by the primary identifier - the run ID in this case.

That's a shame. But it is what it is!

>> Remove the "Versions: 2.6.0, 3.3.2, 3.12.0" next to the Seqera Platform CLI header. Doesn't make any sense having that there and better to include pipeline versions in the General stats table

> Disagree on this point - that's the version of the CLI that was used. It's a core MultiQC feature now, not sure that it hurts to report this?

You sure? Those look like pipeline versions to me? There should only be a single version for the CLI which I agree would be good to include.

>> Change x-axis labels to repository name and instead show Run id on hover.

> Not sure if this is possible, I have a feeling that these need to be unique during report generation (though can be renamed interactively).

Given that those run ids are essentially random strings, they mean nothing to anyone without additional metadata if we just look at that plot. Be great if we can find some sort of workaround to make that more intuitive by default.

2023-11-01 14:07 UTC, ewels commented
> You sure? Those look like pipeline versions to me?

That's a bug in the module if so, 'cc @vladsavelyev 

> Be great if we can find some sort of workaround to make that more intuitive by default.

Best I can think of is the run name, instead of ID? It has to be unique to each run so it doesn't leave us with much. But as mentioned in https://github.com/ewels/MultiQC_TestData/pull/298#issuecomment-1788858338:

> Bit of a shame that there's no other label for the runs beyond the somewhat obscure run ID. But could easily switch these out with something custom using `--sample-names`: https://multiqc.info/docs/reports/customisation/#sample-name-replacement

2023-11-01 17:47 UTC, drpatelh commented
I don't think the version of the Seqera Platform CLI is actually dumped anywhere in those JSON files. I didn't follow how you are now including versions for tools in MultiQC? For the moment, I am doing this manually via the pipeline at the end of a Nextflow process like this:

```
cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        seqera-cli: \$(echo \$(tw --version 2>&1) | sed 's/^.*Tower CLI version //; s/ *\$//')
    END_VERSIONS
```

The versions we can get from the JSON files that we can include in the General Stats table are:
- Nextflow Version (`workflow.json['nextflow']['version']`)
- Seqera Platform Version (`service-info.json['version']`)

2023-11-01 18:22 UTC, vladsavelyev commented
Updated version:

<img width="1058" alt="Screenshot 2023-11-01 at 19 03 56" src="https://github.com/ewels/MultiQC/assets/1575412/671203ff-8dbf-4a2c-9923-405659332d05">

One thing I'm not sure about is putting all the 3 versions into the table as columns. It is already too wide for a laptop screen, and as mentioned before, we have a separate mechanism in MultiQC for the tool/software version reporting, so the platform and the nextflow versions (and the CLI version if provided) should perhaps be reported there (see the screenshot), and we can just add one column for the pipeline versions as it will more likely be different between runs.

We can also add the nextflow/platform versions as hidden columns if it's useful for table exporting 🤔

2023-11-01 18:23 UTC, vladsavelyev commented
Regarding the run names, it would be nice to append the repository IDs to the run IDs and make them clickable, instead of having a separate column. This way, the IDs would be more meaningful in the plots as well. That would need some adjustments in the core MultiQC.

2023-11-01 18:58 UTC, ewels commented
I don't think that we should touch the run IDs. I think we should suggest to the user to use a second separate manually created CSV to use with `--sample-names` or `--replace-names`, as a meaningful identifier will be custom for every run.

The pipeline doing these runs could potentially generate such a file, if there is logic in the workflow to do so.

2023-11-01 18:59 UTC, ewels commented
> We can also add the nextflow/platform versions as hidden columns if it's useful for table exporting 🤔

I think this is good, if nothing else so that if there is more than one value you can see which run used which.

2023-11-02 08:15 UTC, drpatelh commented
> I think this is good, if nothing else so that if there is more than one value you can see which run used which.

Think it's fine to scroll of the screen and not hiding? Having versions per run will be quite useful as a sanity check too ensure exactly which versions were used for each run as they could be different across a run set.

Can we label the y-axis in the plots by repository name somehow and then show the run id on hover? Or is that a no-go?

I will look into the labels aspect when I'm on a laptop as I think that would be incredibly useful to help with filtering and visualisation.

2023-11-02 09:19 UTC, drpatelh commented
> Think it's fine to scroll off the screen and not hiding? Having versions per run will be quite useful as a sanity check to ensure exactly which versions were used for each run as they could be different across a run set.

As a compromise, maybe we can add the `Nextflow Version` to the General Stats and leave the Seqera Platform in the versions section at the bottom of the report as you have done already @vladsavelyev . It's quite unlikely that the latter will be different across pipeline runs.

2023-11-02 13:23 UTC, vladsavelyev commented
Sharing an updated version:

<img width="1164" alt="Screenshot 2023-11-02 at 14 22 17" src="https://github.com/ewels/MultiQC/assets/1575412/0ffbb741-2f84-4b7b-bf17-634e5d3992c2">

Figured it would be nice to color the platform/nextflow versions with colored badges, as otherwise it's hard to tell apart outliers in the list :)

2023-11-02 13:30 UTC, vladsavelyev commented
Done! (updated the comment above)

2023-11-02 14:06 UTC, drpatelh commented
Beautiful! Last main thing to add would be the Plots I outlined in https://github.com/ewels/MultiQC/pull/2151#issuecomment-1788912050

I have created issues on the Seqera CLI for things that would be good to add in the future. For now, I can try to find a workaround for using run names in the plots via a mapping file.

Copied again below:

## Additional Plots

It would be great to at least have bar plots for the more pertinent metrics so they can be dumped directly into presentations if required rather than having to generate them via another tool:

- [ ] CPU Time
- [ ] Wall Time
- [ ] Estimated cost ($)

2023-11-02 14:47 UTC, vladsavelyev commented
> It would be great to at least have bar plots for the more pertinent metrics so they can be dumped directly into presentations if required rather than having to generate them via another tool:

I'm not sure I understand though what would be the categories in such bar plots. In the dump, there is only one value per run, which fits a table column - which translates into a simple bar plot by the means of the background color bar:

<img width="198" alt="Screenshot 2023-11-02 at 15 44 40" src="https://github.com/ewels/MultiQC/assets/1575412/44e53b63-7092-4125-9844-a7f185827c51">

But that doesn't fit a bar plot, where you want multiple non-overlapping categories that can sum up.

If we had per-process numbers, that might work - we could use the N heaviest processes as categories, plus "the remaining" as the last tail category.

2023-11-02 14:49 UTC, drpatelh commented
We would have a separate plot for each metric so which should be relatively simple?

2023-11-02 14:58 UTC, vladsavelyev commented
Such a plot for a single-value metric would just duplicate the corresponding table column.

<img width="893" alt="Screenshot 2023-11-02 at 15 55 37" src="https://github.com/ewels/MultiQC/assets/1575412/d511b0d8-ceea-4832-99d9-32afd768d35c">

We do have this plot in the table already:

<img width="433" alt="Screenshot 2023-11-02 at 15 57 20" src="https://github.com/ewels/MultiQC/assets/1575412/945ea4f3-c44b-4edb-a4ac-5da4d21bdf27">

2023-11-02 15:11 UTC, drpatelh commented
Yes, exactly! One for each of the metrics I listed. The problem with having that in the table is you can't export it as a plot. Also, it will be nice to bring a larger focus on the core metrics if we have individual plots.

2023-11-02 17:28 UTC, vladsavelyev commented
Alright, let's add those. It would be nice to add per-process data into the run dump though, to make the bars more informative.

[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/13242750/multiqc_report.html.zip)

<img width="937" alt="Screenshot 2023-11-02 at 18 26 24" src="https://github.com/ewels/MultiQC/assets/1575412/b47258a8-c869-4ad2-9503-915de7f5c40b">

2023-11-02 17:55 UTC, drpatelh reviewed
Looks awesome @vladsavelyev ! 🤩 Thank you! Some minor comments for consistency but otherwise LGTM! Be great to add in some other things in the future but this is definitely a good start.

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +            name="Processes statuses",
```suggestion
            name="Workflow status",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                    "title": "Seqera platform CLI: processes statuses",
```suggestion
                    "title": "Seqera platform CLI: Workflow status",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                    "ylab": "Number of processes",
```suggestion
                    "ylab": "Number of tasks",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                    "title": "Seqera platform CLI: wall time",
```suggestion
                    "title": "Seqera platform CLI: Wall time",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +            name="Wall Time",
```suggestion
            name="Wall time",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +            name="CPU Time",
```suggestion
            name="CPU time",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                    "ylab": "hours",
```suggestion
                    "ylab": "CPU hours",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +            name="Estimated Cost",
```suggestion
            name="Estimated cost",
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                {"cost": {"name": "Estimated Cost"}},
```suggestion
                {"cost": {"name": "Estimated cost"}},
```

2023-11-02 17:55 UTC, drpatelh commented on multiqc/modules/seqera_cli/seqera_cli.py
> +                    "title": "Seqera platform CLI: estimated cost",
```suggestion
                    "title": "Seqera platform CLI: Estimated cost",
```

2023-11-02 18:27 UTC, drpatelh approved these changes

2023-11-02 20:10 UTC, merged

2023-11-03 13:55 UTC, ewels commented
Looks great! 👏🏻